version: '3'

networks:
    kon-check:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            -   "8080:80"
        volumes:
            -   ./src:/var/www
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            -   mysql
        networks:
            -   kon-check

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            -   "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            -   kon-check

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            -   ./src:/var/www
        ports:
            -   "9000:9000"
        networks:
            -   kon-check